version: 1
author: Fish-Face
language: Rust
dockerfile: .docker/Dockerfile
#image: rust:1.74-alpine
code: /code
workdir: /code
runonce: cargo build --release --bin "day-%zeroday%"
cmd: target/release/day-%dayzero% inputs/day-%zeroday%
persistence:
  - /usr/local/cargo/registry
daypath: src/bin/day-%zeroday%.rs
inputfile: inputs/day-%zeroday%
answerfile: answers/day-%zeroday%
common:
  - .cargo/config.toml
  - src/common.rs
  - src/grid.rs
  - src/coord.rs
